import type {Result} from './model.js';
import {evaluateContinuation,gates,gateIds,type Continuation} from './continuation.js';

export function continuationPanel(r:Result,lens:Continuation){
  const e=evaluateContinuation(r,lens),route=lens.route;
  const facts=[r.civilisation.crossedAt!==null?'The service-collapse threshold was crossed.':'The service-collapse threshold was not crossed.',
    r.nuclear?'The military branch reaches nuclear use; its damage is not calculated.':r.pathways.healthIntroduced?'The health threat is introduced; demand for care is calculated, not deaths.':'No nuclear use or introduced health threat is present.',
    r.pathways.controlLost?r.pathways.harmfulOperation?'The harmful agent continues after its stop order.':'The agent resists stopping, but has no harmful goal here.':'The model does not show a failed stop order.'];
  const headlines={ 'not-started':'This route has no starting event in your world.',interrupted:'Your assumptions leave a way to survive.',unresolved:'The chain still has unanswered questions.',assumed:'Every remaining line of defence is assumed to fail.'};
  const explanation=!e.started?'You can explore the extra conditions, but they do not create a new event on the board.':e.blockers.length?gates[route][e.blockers[0]].barrier:e.unknowns.length?'Open a link to examine what would also need to be true. An unanswered question is not a failed safeguard.':'These choices complete a proposed chain of conditions. They do not calculate whether every human dies.';
  return `<div class="continuation-intro"><p>THE SURVIVORS · A catastrophe can leave people alive. Could it also take away their food, shelter and ways to rebuild?</p><details class="model-details"><summary>What your world actually shows</summary><ul>${facts.map(f=>`<li>${f}</li>`).join('')}</ul><p>${r.civilisation.independentRegions} regions are outside this network fault. That does not prove they are safe from other threats.</p><p>The service calculation ends at day 30. It does not track every person or long-term survival.</p></details></div>
  ${!e.started?'<div class="entry-callout"><strong>Your world has not reached this starting point.</strong><p>First explore how essential services could fail across regions. Then follow what happens to survivors.</p><button class="small-button" id="continuation-start">Explore a collapse starting point →</button></div>':''}<div class="continuation-routes" role="group" aria-label="Choose a continuation"><button data-continuation-route="physical" aria-pressed="${route==='physical'}">A physical threat spreads</button><button data-continuation-route="hostile" aria-pressed="${route==='hostile'}">Hostile control persists</button></div>
  <p class="continuation-caption">${route==='physical'?'Imagine survivors trying to find food, clean water and shelter. A widespread physical threat would have to reach them too, defeat their protected places and prevent new communities from rebuilding. Open each link to explore what could stop it.':'An AI that ignores a stop order is not automatically able to reach everyone. Could people disconnect a town, keep machinery under human control, or rebuild somewhere it cannot reach? Explore those remaining defences.'}</p>
  <div class="continuation-links">${gateIds.map((id,i)=>{
    const gate=gates[route][id],value=lens[route][id];
    return `<details class="continuation-gate" data-gate="${id}" data-answer="${value}"><summary><span class="continuation-number">${i+1}</span><span>${gate.title}<small>${value==='unknown'?'Not answered yet':value==='yes'?'You assume yes':'You assume no · this link breaks'}</small></span></summary><p>${gate.why}</p><label for="continuation-${id}">What if…</label><select id="continuation-${id}" data-continuation-gate="${id}"><option value="unknown" ${value==='unknown'?'selected':''}>Not answered yet</option><option value="yes" ${value==='yes'?'selected':''}>Explore if this happens</option><option value="no" ${value==='no'?'selected':''}>This safeguard holds</option></select></details>`;
  }).join('')}</div>
  <div class="continuation-verdict" data-verdict="${e.state}" aria-live="polite"><strong>${headlines[e.state]}</strong><p>${explanation}</p><small>This concerns the selected route. Other threats can still exist.</small></div>
  <button class="small-button" id="continuation-refuge">What if one community stays out of reach? ↗</button><button class="small-button" id="continuation-reset">Reset these assumptions ↶</button>
  <p class="continuation-boundary">Extinction is not resolved by this model.</p>
  <details class="model-details"><summary>Evidence and limits</summary><p>The board supplies the starting facts. Every answer here is a separate thought-experiment assumption, saved with your world. It does not change the service calculation or represent a probability.</p><p>These are two proposed routes, not an exhaustive list or proof that all the conditions would be sufficient. Counting failures is not counting survivors.</p><a class="source-link" target="_blank" rel="noreferrer" href="https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026">International AI Safety Report · uncertainty and loss of control ↗</a><a class="source-link" target="_blank" rel="noreferrer" href="https://www.icrc.org/en/article/faq-nuclear-weapons">ICRC · nuclear consequences ↗</a></details>`;
}
