// Evidence supports a mechanism; numerical choices remain explicit teaching assumptions.
export interface EvidenceNote {mechanism:string; assumption:string; source:'ai'|'military'|'health'|'resilience'|'finance'|'recovery';}
const notes:Record<string,EvidenceNote>={
 ability:{mechanism:'AI risk depends on capability, behaviour and the access people give a system.',assumption:'These three ability levels describe control of services, not a measured intelligence score.',source:'ai'},
 development:{mechanism:'AI-assisted research can accelerate development, while resources and evaluations remain constraints.',assumption:'Up to 20 updates a day and twenty tests a day are teaching scales. User-set mistake rate and testing effectiveness generate caught and escaped faults. Each escaped fault adds repair work; errors are sampled by project identity, not predicted from real AI behaviour.',source:'ai'},
 control:{mechanism:'Persistent loss of control requires capabilities, behaviour and an enabling environment together.',assumption:'This route assumes an agent can resist stopping and keep reaching the network. It does not establish that current systems can take over society.',source:'ai'},
 military:{mechanism:'Unreliable AI advice and over-reliance under time pressure can impair military decisions.',assumption:'The warning, response cutoffs and human-choice odds are authored. An outage does not normally imply an attack warning. Leaders retain weapons authority.',source:'military'},
 nuclear:{mechanism:'A mistaken military decision can have consequences far beyond the original information failure.',assumption:'Nuclear use is a separate assumed human choice after escalation. The model does not simulate blast damage, fallout or subsequent food loss.',source:'military'},
 infrastructure:{mechanism:'Essential services depend on communications, energy and transport. Shared dependencies can spread one failure.',assumption:'Here a shared control failure can stop power. This is a chosen vulnerable architecture, not a claim that every phone outage cuts electricity.',source:'recovery'},
 health:{mechanism:'Surveillance, response capacity, staff and access to supplies support health-system resilience.',assumption:'The demand wave and recovery shape are a stress test, not epidemic dynamics. AI assistance, harmful intent, physical access and failed screening are separate prerequisites.',source:'health'},
 information:{mechanism:'AI-generated manipulation can impair people’s ability to make informed decisions.',assumption:'This campaign weakens emergency coordination for a chosen duration. Its numerical effect is an assumption, not a measured persuasion rate.',source:'ai'},
 finance:{mechanism:'Shared technology providers can create common operational vulnerabilities in finance.',assumption:'Only payment availability constrains deliveries here. Banking contagion, asset prices and credit collapse are outside this model.',source:'finance'},
 recovery:{mechanism:'Damaged infrastructure and its dependencies affect restoration and community resilience.',assumption:'One repair job represents the shared fault. Crew multipliers are teaching choices. A relief package bundles crews, powered tools, parts and food; its budget is finite.',source:'recovery'},
 collapse:{mechanism:'Continuity of essential services and government response are linked resilience concerns.',assumption:'The lamp tests sustained multi-region service failure. It is not a complete definition of societal collapse: health-only and nuclear catastrophes can exceed its scope. Recovery and extinction remain separate questions.',source:'resilience'},
 food:{mechanism:'Energy and transport failures can interrupt essential supplies.',assumption:'Cold storage and food availability are separate. Stores cover delivery shortfalls until empty; farming, nutrition, water and deaths are not simulated.',source:'resilience'}
};
const groups:Record<string,string>={ai:'ability',access:'ability',development:'development',control:'control',checks:'military',warning:'military',military:'military',nuclear:'nuclear',comms:'infrastructure',power:'infrastructure',fallback:'infrastructure',spread:'infrastructure',transport:'infrastructure',hospital:'health',bio:'health',information:'information',payments:'finance',repair:'recovery',recovery:'recovery',crews:'recovery',supplies:'recovery',aid:'recovery',emergency:'recovery',governance:'collapse',collapse:'collapse',food:'food'};
export function evidenceFor(id:string):EvidenceNote{return notes[groups[id]];}
