import {DEFAULTS,type Settings} from './model.js';
import {settingNames,settingValue} from './protection.js';
import {pathwayPresets,scenarioNames} from './pathway-ui.js';
const names:Partial<Record<keyof Settings,string>>={...settingNames,waitForChecks:'Hold updates until tested',agentEnabled:'AI agent',harmfulGoal:'Agent disrupts services',externalResources:'Agent has outside resources',independentStop:'Independent disconnect',healthChallenge:'Health threat',scienceAssistance:'AI science help',maliciousActor:'Someone intends harm',physicalAccess:'Physical access',screening:'Threat screening',informationCampaign:'False emergency messages',informationReach:'Response put at risk',trustedChannels:'Trusted channels',informationHours:'False-message duration',sharedPayments:'Payments depend on the network',sharedTransport:'Transport depends on the network',paymentFallback:'Offline payments',transportFallback:'Independent transport',foodStores:'Food stores',capability:'AI abilities',authority:'Permissions',tension:'World tension',fallback:'Independent services',researchSpeed:'AI project pace'};
export const scenarioMeaning:Record<string,string>={calm:'Thirty updates a month, with enough time to check every one. Services hold. Try raising AI project pace to 48 updates a month: some updates can now outrun the checks. How far can you push this world?',outage:'AI produces updates faster than this world checks them. Some mistakes escape. Can people keep essentials working?',research:'AI projects release updates without waiting for checks. More releases create more chances for mistakes to escape.',control:'An agent ignores its stop order and keeps undoing repairs. Project pace is zero so you can explore the agent on its own.',health:'A health threat gets past screening. Demand overwhelms hospitals even if the phone network works.',information:'False emergency messages make it harder for people to organise a response.',deliveries:'Payments and transport rely on the failed network. Food and repair supplies become harder to get.'};
export function scenarioChanges(before:Settings,id:string){const next={...DEFAULTS,...pathwayPresets[id]};return (Object.keys(next) as (keyof Settings)[]).filter(k=>before[k]!==next[k]).map(key=>({key,before:before[key],after:next[key],name:names[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}));}
export function scenarioReceipt(before:Settings,id:string,dials:string[]){
 const changes=scenarioChanges(before,id),main=changes.filter(c=>dials.includes(c.key)),other=changes.filter(c=>!dials.includes(c.key));
 const row=(c:typeof changes[number])=>`<button data-setting-reveal="${c.key}"><span>${c.name}</span><b>${settingValue(c.key,c.before)} → ${settingValue(c.key,c.after)}</b></button>`;
 return `<section class="scenario-receipt"><span class="etched-label">SCENARIO LOADED</span><h3>${scenarioNames[id]}</h3><p>${scenarioMeaning[id]}</p><p><strong>${main.length?`${main.length} main dial${main.length===1?'':'s'} changed.`:'The main dials stay the same.'}</strong> ${other.length?`${other.length} other setting${other.length===1?'':'s'} changed below.`:''}</p>${main.map(row).join('')}${other.slice(0,3).map(row).join('')}${other.length>3?`<details><summary>${other.length-3} more changed settings</summary>${other.slice(3).map(row).join('')}</details>`:''}<p>Click a setting to find its control.</p><button id="scenario-receipt-close">Got it · explore this scenario →</button><button id="scenario-undo">↶ Undo this scenario</button></section>`;
}
