import type {Result} from './model.js';
import {evaluateContinuation,gateIds,type Continuation,type Gate,type Route} from './continuation.js';
export const survivalQuestions:Record<Route,Record<Gate,{title:string;scene:string;yes:string;no:string;lost:string;saved:string}>>={
 physical:{
  power:{title:'Can people stay alive?',scene:'The city has gone dark. Families need clean water, food and somewhere safe to sleep. Imagine the damage becomes severe enough to threaten their lives.',yes:'Essentials fail',no:'People keep essentials',lost:'Families lose the essentials they need to stay alive. Next, look for places the danger cannot reach.',saved:'People keep enough food, water and shelter to survive. This catastrophe has not taken away every chance of life.'},
  reach:{title:'Is anywhere beyond reach?',scene:'Think of an island, a remote village or a community with its own supplies. Does the danger reach every one of them?',yes:'Nowhere escapes',no:'Somewhere stays safe',lost:'There is no untouched place to escape to in this story. Could a protected shelter still keep people alive?',saved:'A community remains beyond the danger. Even if cities fall, humanity still has a foothold.'},
  protection:{title:'Do safe places hold?',scene:'Survivors shelter behind independent power, stored food, clean water and practical defences. Imagine whether those protections last.',yes:'Safe places fail',no:'Safe places hold',lost:'The refuges fail too. The last question is whether people can find a way to recover.',saved:'A refuge holds. People have a place to survive while the world outside is in danger.'},
  recovery:{title:'Can people rebuild?',scene:'A terrible first month is not the end of history. Survivors might grow food, repair equipment and build communities again.',yes:'Recovery is blocked',no:'People rebuild',lost:'In this story the remaining communities cannot recover or keep themselves alive.',saved:'Survivors find a lasting way forward. Civilisation may change completely, but the human story continues.'}
 },
 hostile:{
  power:{title:'Can it act beyond computers?',scene:'Ignoring a stop button is one thing. Controlling equipment that people need for food, water and shelter is another. Imagine that extra power.',yes:'It controls vital equipment',no:'It stays confined',lost:'Its harmful actions can threaten lives outside the computer. Can any community stay outside its reach?',saved:'It cannot turn its computer access into a threat to every human life. This route is blocked here.'},
  reach:{title:'Can anyone disconnect?',scene:'A town switches to local equipment and independent supplies. Could somewhere like this stay outside the agent’s control?',yes:'It reaches everyone',no:'A community disconnects',lost:'No community escapes its reach in this story. Could an independent defence still hold?',saved:'A disconnected community survives beyond its control. Humanity still has a foothold.'},
  protection:{title:'Can a defence hold?',scene:'People isolate equipment, protect supplies and keep machines under local control. Can any of these defences preserve a community?',yes:'Every defence fails',no:'A defence holds',lost:'The independent defences fail too. Can people eventually regain control or rebuild?',saved:'An independent defence protects people. The agent has not closed every way to survive.'},
  recovery:{title:'Can people take back control?',scene:'An agent that resists stopping for a month need not stay in control forever. People could cut off its resources or rebuild outside its control.',yes:'It keeps defeating recovery',no:'People regain control',lost:'It keeps preventing the remaining communities from recovering or sustaining life in this story.',saved:'People regain a lasting way to live and rebuild. The threat does not end the human story.'}
 }
};
export function survivalVerdict(r:Result,lens:Continuation){
 const e=evaluateContinuation(r,lens);
 return e.state==='not-started'?{title:'Choose a starting threat',copy:'Choose another threat, or load its starting scenario.'}:e.state==='interrupted'?{title:'A way to survive remains',copy:survivalQuestions[lens.route][e.blockers[0]].saved}:e.state==='assumed'?{title:'No refuge remains in your story',copy:'You have imagined a threat that reaches everyone, defeats their defences and prevents recovery. This sketches a possible route to extinction—not proof that these events would happen or that every person would die.'}:{title:'The survivors still have options',copy:`${e.unknowns.length} question${e.unknowns.length===1?' is':'s are'} still open. Try the next defence to see how the story changes.`};
}
export function continuationPanel(r:Result,lens:Continuation,active:Gate='power'){
 const e=evaluateContinuation(r,lens),v=survivalVerdict(r,lens),q=survivalQuestions[lens.route][active],value=lens[lens.route][active],index=gateIds.indexOf(active),next=gateIds[(index+1)%4];
 const otherRoute:Route=lens.route==='physical'?'hostile':'physical',otherStarted=evaluateContinuation(r,{...lens,route:otherRoute}).started;
 const start=lens.route==='hostile'?'The harmful agent is still acting after its stop order.':r.nuclear?'Nuclear weapons have been used.':r.pathways.healthIntroduced?'An AI-assisted health threat has reached people.':'Essential services have failed together across regions.';
 return `<button class="small-button" data-stage="damage">← Back to the live world</button><div class="continuation-routes" role="group" aria-label="Threat to survivors"><button data-continuation-route="physical" aria-pressed="${lens.route==='physical'}">A catastrophe</button><button data-continuation-route="hostile" aria-pressed="${lens.route==='hostile'}">An unstoppable agent</button></div>
 ${!e.started?`<div class="survival-entry"><h2>${lens.route==='hostile'?'This world has no unstoppable harmful agent.':'Your world has not reached this catastrophe.'}</h2><p>To follow the survivors, begin with ${lens.route==='hostile'?'an agent that ignores a stop order':'widespread failure of essential services'}.</p>${otherStarted?`<button class="primary-action" data-continuation-route="${otherRoute}">Follow this world’s ${otherRoute==='physical'?'catastrophe':'harmful agent'} →</button><p>Or try a different starting threat:</p>`:''}<button class="primary-action" id="continuation-start">Load ${lens.route==='hostile'?'the harmful-agent':'a collapse'} scenario →</button><p>This replaces world settings. Undo brings your world back.</p></div>`:`<p class="survival-fact"><span class="etched-label">FROM YOUR WORLD</span>${start}</p><span class="etched-label">WHAT IF · DEFENCE ${index+1} OF 4</span><h2 class="inspector-title">${q.title}</h2><p class="inspector-copy">${q.scene}</p><p class="choice-instruction">Choose one of the two endings on the card.</p>${value!=='unknown'?`<div class="survival-consequence ${value}" role="status">${value==='yes'?q.lost:q.saved}</div>`:''}<button class="primary-action" data-gate-open="${next}">${index===3?'Revisit the first defence':`Next: ${survivalQuestions[lens.route][next].title}`} →</button><button class="text-button" data-survival-answer="unknown" data-gate="${active}">Leave this question open</button>`}
 ${e.started?`<div class="continuation-verdict" data-verdict="${e.state}" aria-live="polite"><span class="etched-label">YOUR SURVIVAL STORY</span><strong>${v.title}</strong><p>${v.copy}</p></div>`:''}${e.started?'<button class="small-button" id="continuation-refuge">Give one community a safe place →</button><button class="small-button" id="continuation-reset">Start the survival story again ↶</button>':''}<details class="model-details"><summary>What is calculated, and what am I choosing?</summary><p>The starting event comes from your world. These four answers are what-if choices, not new calculations or changes to the main dials. Their effects appear on the survival canvas and in the story above.</p><p>Collapse and extinction are different. The model follows services for 30 days, not every person for the rest of time. These are proposed routes, not a complete list of everything that would be required for extinction.</p><a class="source-link" target="_blank" rel="noreferrer" href="https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026">AI Safety Report · evidence and uncertainty ↗</a></details>`;
}
export function survivalCanvas(r:Result,lens:Continuation,active:Gate){
 const e=evaluateContinuation(r,lens),v=survivalVerdict(r,lens),positions=[[65,170],[595,170],[65,410],[595,410]];
 const otherRoute:Route=lens.route==='physical'?'hostile':'physical',otherStarted=evaluateContinuation(r,{...lens,route:otherRoute}).started;
 return `<g class="survival-canvas"><text x="65" y="55" class="survival-heading">THE LAST REFUGES</text><text x="65" y="89" class="survival-caption">${e.started?'Your what-if story · choose an ending on each card.':'Load a starting scenario here, then choose what happens on each card.'}</text>${!e.started?`<foreignObject x="65" y="103" width="950" height="50"><div xmlns="http://www.w3.org/1999/xhtml" class="canvas-start">${otherStarted?`<button data-continuation-route="${otherRoute}">Follow this world’s ${otherRoute==='physical'?'catastrophe':'harmful agent'} →</button>`:`<button data-survival-start="true">Load ${lens.route==='hostile'?'the harmful-agent':'a collapse'} scenario →</button><span>Replaces world settings · Undo brings them back</span>`}</div></foreignObject>`:''}<path class="survival-trail" d="M290 270 H820 V390 H290 V495 H820"/>${gateIds.map((id,i)=>{
  const [x,y]=positions[i],value=lens[lens.route][id],q=survivalQuestions[lens.route][id],state=!e.started?'quiet':value==='yes'?'harm':value==='no'?'safe':'exposed';
  return `<g transform="translate(${x} ${y})" class="machine-node survival-stop ${state} ${e.started&&id===active?'selected':''}" role="group" aria-label="Defence ${i+1}"><rect class="socket" width="420" height="175" rx="16"/><rect class="selection-ring" x="8" y="8" width="404" height="159" rx="10"/><g role="${e.started?'button':'img'}" tabindex="${e.started?'0':'-1'}" ${e.started?`data-gate-open="${id}"`:``} aria-label="Defence ${i+1}: ${q.title}"><rect width="420" height="94" fill="transparent"/><text x="25" y="32" class="survival-step">DEFENCE ${i+1} / ${!e.started?'WAITING':value==='yes'?'LOST IN YOUR STORY':value==='no'?'HOLDS IN YOUR STORY':'CHOOSE BELOW'}</text><text x="25" y="73" class="survival-question">${q.title}</text></g>${e.started?`<foreignObject x="20" y="101" width="380" height="58"><div xmlns="http://www.w3.org/1999/xhtml" class="canvas-choices"><button data-canvas-choice="true" data-survival-answer="yes" data-gate="${id}" aria-pressed="${value==='yes'}">${q.yes}</button><button data-canvas-choice="true" data-survival-answer="no" data-gate="${id}" aria-pressed="${value==='no'}">${q.no}</button></div></foreignObject>`:'<text x="25" y="130" class="survival-answer">Load a starting scenario first →</text>'}<circle class="module-led" cx="385" cy="30" r="7"/></g>`;
 }).join('')}<g class="survivor-settlement ${e.state}"><path d="M75 693L110 665L145 693V733H75Z M160 693L195 660L230 693V733H160Z M245 693L280 665L315 693V733H245Z"/><path class="windows" d="M96 700h13v16H96z M187 698h14v18h-14z M269 700h13v16h-13z"/><text x="350" y="686" class="survival-ending">${v.title}</text><text x="350" y="725" class="survival-caption">${e.state==='assumed'?'Restore one defence. Does a way to survive reopen?':e.state==='interrupted'?'A surviving community keeps the human story open.':e.started?'Four defences. More than one possible ending.':'Choose another threat, or load its starting scenario.'}</text></g></g>`;
}
export function threatReadouts(r:Result,lens:Continuation){
 const c=r.civilisation,e=evaluateContinuation(r,lens),level=r.nuclear?3:c.endStatus==='collapse'?3:c.endStatus==='disrupted'?2:r.incident?1:0;
 const title=r.nuclear?'Nuclear catastrophe':c.endStatus==='collapse'?'Civilisation in crisis':c.endStatus==='recovered'?'Rebuilding after collapse':c.endStatus==='disrupted'?'Lifelines under strain':r.incident?'Services recovered':'World holding';
 return `<div class="threat-readout level-${level}" title="Calculated world condition. Open Read the damage to explore it."><span>WORLD CONDITION</span><strong>${title}</strong><i class="threat-segments" aria-hidden="true">${[0,1,2,3].map(i=>`<b class="${i<=level?'lit':''}"></b>`).join('')}</i><small>${r.nuclear?'Event shown · aftermath unknown':'Calculated service outcome'}</small></div><div class="threat-readout survival-${e.state}" title="Your survival what-if. Open Beyond collapse to explore it."><span>COULD ANYONE SURVIVE?</span><strong>${!e.started?'Not explored':e.state==='interrupted'?'A way to survive remains':e.state==='assumed'?'No refuge in your story':`${4-e.unknowns.length} of 4 explored`}</strong><i class="threat-segments" aria-hidden="true">${gateIds.map(id=>`<b class="${!e.started?'':lens[lens.route][id]==='yes'?'lost':lens[lens.route][id]==='no'?'held':''}"></b>`).join('')}</i><small>Your what-if story · ${e.started?`${4-e.unknowns.length}/4 defences explored`:'choose a starting threat'}</small></div>`;
}
